// summer-ospp/2022/MaxKey-React/src/routes/AppList.tsx
import React,{useEffect,useState} from "react"
import {api} from "../utils/api"
import {baseUrl} from "../utils/api"
import {AxiosResponse,AxiosError} from "axios"
import {message,Spin} from "antd"
import "../assets/scss/applist.scss"
export default function AppList(){
    const [appList,setAppList] = useState<Array<any>>([])
    const [loading,setLoading] = useState<boolean>(true)
    useEffect(()=>{
        api.appList()
        .then((res:AxiosResponse)=>{
            if(res.data.code===0){
                setAppList(res.data.data)
                setLoading(false)
            }          
        })
        .catch((err:AxiosError)=>{
            message.error(err.message)
            Promise.reject(err)
        })

    },[])
    const onAuthz = (e: React.MouseEvent<HTMLElement>,appId:string):void=>{
        e.preventDefault()
        for(let i = 0;i < appList.length; i++){
            if(appList[i].id === appId &&(appList[i].protocol === 'Basic' || appList[i].inducer === 'SP')){
                window.open(appList[i].loginUrl);
                return;
            }
        }
        window.open(`${baseUrl}/authz/${appId}`)
    }
    return (
        <Spin spinning={loading}>
            <ul>           
            {appList.length>0&&appList.map((app:any)=>
                <li onClick={(e)=>onAuthz(e,app.id)} key={app.id}><img src={app.iconBase64} alt=""/></li>
            )}        
            </ul>
        </Spin>
        

    )
}

// summer-ospp/2022/MaxKey-vue/src/components/AppList.vue
<template>
    <ul>
        <template v-for="app in appList">
            <li @click="onAuthz($event,app.id)"><img :src="app.iconBase64" alt=""/></li>
        </template> 
    </ul>   
</template>

<script lang="ts" setup>
import { ElMessage } from 'element-plus';
import { onBeforeMount,ref } from 'vue';        
import {api} from "../utils/api"
import {baseUrl} from "../utils/api"

let appList = ref([])
onBeforeMount(()=>{
    api.appList()
    .then((res)=>{       
        appList.value = res.data.data
    })
    .catch(err=>{
        ElMessage.error(err.message)
        Promise.reject(err)
    })  
})

const onAuthz=(e:MouseEvent,appId:string):void=>{
    e.preventDefault()
    for(let i = 0;i < appList.value.length; i++){
        if(appList.value[i].id === appId &&(appList.value[i].protocol == 'Basic' || appList.value[i].inducer == 'SP')){
            window.open(appList.value[i].loginUrl);
            return
        }
    }
    window.open(`${baseUrl}/authz/${appId}`)
}
</script>

<style lang="less" scoped>
ul {
    display: flex;
    flex-wrap: wrap;
    li {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 254px;
        height: 127px;
        background-color: #fff;
        margin-right: 24px;
        margin-bottom: 12px;
        img {
            height: 65px;
            width: 65px;
        }
        &:hover {
            cursor: pointer;
            box-shadow: 
                0px 2px 5px 3px rgba(0,0,0,0.15) ;
                
        }
    }
    &>li:nth-child(4n){
        margin-right: 0;
    }
}
 

</style>
