// summer-ospp/2022/MaxKey-vue/src/components/login.vue
<template>
    <div>
        <Header />
        <form class="form-signin" method="post" >
          <h3>业界领先的IAM身份管理和认证产品</h3>
          <div class="login-type" :class="isqrCode ? 'activeTwo' : 'activeOne'">
            <span @click="switchTab(1)" >
              <i><Icon iconClass="user" class="user"></Icon></i>
              账号登录
            </span>
            <span @click = "switchTab(2)">
              <i><Icon iconClass="erweima"></Icon></i>
              扫码登录
            </span>
          </div>
          <template v-if = "!isqrCode">
            <div class="username">
              <label for="username" class="label">
                <Icon iconClass="user" class="erweima"></Icon>
              </label>
              <input 
              v-model="form.username"
              type="text" 
              name="username" 
              id="username" 
              class="form-control" 
              placeholder="用户名"
              />
            </div>
            <div class="password">
              <label for="inputPassword" class="label">
                  <Icon iconClass="key"></Icon>
              </label>
              <input 
              v-model="form.password"
              :type= "passwordType"
              name="password" 
              id="inputPassword" 
              class="form-control" 
              placeholder="密码" required/>
              <i @click="show" v-show="visible">
                  <Icon 
                iconClass="eyes-open"
                class="eyes-img"
                />
              </i>             
              <i @click="show" v-show="!visible">
                  <Icon 
                      iconClass="eyes-close"      
                      class="eyes-img"/>
              </i>            
            </div>
            <div class="check">
              <label for="check" class="label">
                <Icon iconClass="lock"/>
              </label>
              <input
              type="text"
              id="check"
              placeholder="验证码"
              class="form-control" 
              v-model="form.captcha"        
              />           
              <div class="code">
                <img :src="imageCaptcha" @click="getImageCaptcha" alt=""/>
              </div>
            </div>          
            <div class="remember">
              <input type="checkbox" id="remember" v-model="rememberMe" />
              <label for="remember">记住登录</label>
              <router-link to="/passport/forgot">忘记密码</router-link>
            </div>              
            <button type="button" class="btn"  @click="login" >登录</button>
            <div class="otherLogin">
              <span> 其他登录方式 </span>
                <template
                  v-for="prod in providers"
                  >
                  <img :src= 'prod.icon' alt="" width="32px" @click="socialauth(prod.provider)">                
                  </template>                                 
            </div>
        </template>
        <div v-if="isqrCode">
          <div id="div_qrcodelogin"></div>
        </div>          
      </form>     
      <Footer/>
    </div>   
</template>

<script lang="ts" setup>
import { AxiosError,AxiosResponse} from 'axios'
import {api} from "../utils/api"
import {reactive,ref,onBeforeMount, onBeforeUpdate} from "vue"
import CONSTS from "../shared/index"
import Icon from "./Icon.vue"
import {ElLoading,ElMessage} from "element-plus"
import {useRouter} from "vue-router"
import Header from "./Header.vue"
import Footer from "./Footer.vue"
interface Form {
    username: string,
    password: string,
    captcha: string ,
     
}

let state=""
let captchaType = ""
let loginType="normal"
const router = useRouter()

const form = reactive<Form>({
        username:"",
        password:"",
        captcha:"", 
    })
const rememberMe = ref<boolean>(false)
const isqrCode  =ref<boolean>(false)
let passwordType=ref("password")
let visible=ref(false)
let imageCaptcha= ref<string>("")

let providers = ref<object[]>([])//reactive不可以监视？
let qrScan = ""
const getUrl=(value:string)=>{
  let params=window.location.search.substring(1).split("&")
  for(let i = 0; i < params.length; i++){
    let param=params[i].split('=')
    if(param[0]===value){
      return param[1]
    }
  }
  return '';
}

const socialauth=(provider:string): void =>{
  //clear User
  localStorage.setItem('user',JSON.stringify({}))
  api.authorize(provider)
  .then((res)=>{
    // debugger
    window.location.href = res.data.data
  })
}

const congressLogin=(congress:string)=>{
  api.congress({congress:congress})
    .then((res: AxiosResponse)=>{
      res=res.data
      if(res.code !== 0){
        console.log(res.msg)
      }else{
        //设置用户token信息
        api.auth(res.data)
        api.navigate({})
      }     
    })
    .catch((err:AxiosError)=>{
      console.log(err.message)
      Promise.reject(err)
    })
}

onBeforeMount(()=>{
  if(getUrl(CONSTS.REDIRECT_URI)!==''){
    api.setRedirectUri(getUrl(CONSTS.REDIRECT_URI))
  }
  if(getUrl(CONSTS.CONGRESS)){
    congressLogin(getUrl(CONSTS.CONGRESS))
  }
  //init socails,state
  api.clear()
  
  api.get({remember_me:localStorage.getItem(CONSTS.REMEMBER)})
    .then((res:AxiosResponse)=>{
      res=res.data
      if(res.code != 0){
        console.log(res.msg)
      }else{        
        if(res.data.state){          
          providers.value=res.data.socials.providers
          qrScan = res.data.socials.qrScan
          state =res.data.state
          captchaType = res.data.captcha
          if(captchaType !== 'NONE'){
            //初始化图像验证码
            api.getImageCaptcha({state,captcha:captchaType})
              .then((res)=>{
                res=res.data
                imageCaptcha.value=res.data.image
              })
          }
        }
      }
    })
    .catch((err:AxiosError)=>{
      Promise.reject(err)
    })

})

const show=()=>{
    visible.value=!(visible.value);
    if(!visible.value)passwordType.value="password"
    else passwordType.value="text"   
}

const getImageCaptcha=():void=>{
  api.getImageCaptcha({state,captcha:captchaType})
  .then((res)=>{
    res=res.data
    imageCaptcha.value=res.data.image;
  })
  .catch(err=>Promise.reject(err))
}

const login=()=>{   
   if(form.username===''|| form.password===''|| form.captcha===''){
      return;
   }
    localStorage.setItem(CONSTS.REMEMBER,rememberMe.value === true?"true":"false")
    api.login(
      {
        authType:loginType,
        state,
        username:form.username,
        password:form.password,
        captcha:form.captcha,
        mobile:null,
        otpCaptcha:null,
        remeberMe:rememberMe.value,
      })
      .then((res:AxiosResponse)=>{            
            res=res.data
            if(res.code!=0){
              //ElMessage.error(res.message)
              getImageCaptcha()
            }else{
              //清空路由复用信息?
              api.auth(res.data)              
              api.navigate({})
              router.push("/dashboard/home")
              
            }                  
           // res.data.token&&localStorage.setItem('token',res.data.token)            
          })
      .catch((err:AxiosError)=>{
          console.log(err.message)
          Promise.reject(err)
      })          
}

const switchTab=(index:number):void=>{
  if(index===1){
    isqrCode.value = false
  }
  if(index===2){
    isqrCode.value=true
    localStorage.setItem('user',JSON.stringify({}))
    api.scanqrcode(qrScan)
    .then((res:AxiosResponse)=>{
      res=res.data
      if(res.code === 0){
        if(qrScan === 'workweixin'){
          qrScanWorkweixin(res.data)
        }else if(qrScan === 'dingtalk'){
          qrScanDingtalk(res.data)
        }else if(qrScan  === 'feishu'){
          qrScanFeishu(res.data)
        }
      }
    })
  }
}

const qrScanWorkweixin=(data: any) => {
    //see doc https://developer.work.weixin.qq.com/document/path/91025
    // @ts-ignore
    let wwLogin = new WwLogin({
      id: 'div_qrcodelogin',
      appid: data.clientId,
      agentid: data.agentId,
      redirect_uri: encodeURIComponent(data.redirectUri),
      state: data.state,
      href: 'data:text/css;base64,LmltcG93ZXJCb3ggLnFyY29kZSB7d2lkdGg6IDI1MHB4O30NCi5pbXBvd2VyQm94IC50aXRsZSB7ZGlzcGxheTogbm9uZTt9DQouaW1wb3dlckJveCAuaW5mbyB7d2lkdGg6IDI1MHB4O30NCi5zdGF0dXNfaWNvbiB7ZGlzcGxheTpub25lfQ0KLmltcG93ZXJCb3ggLnN0YXR1cyB7dGV4dC1hbGlnbjogY2VudGVyO30='
    });
  }
const qrScanFeishu=(data: any)=> {
    //see doc https://open.feishu.cn/document/common-capabilities/sso/web-application-sso/qr-sdk-documentation
    //remove old div
    var qrcodeDiv = document.querySelector('#div_qrcodelogin');
    qrcodeDiv?.childNodes.forEach(function (value, index, array) {
      qrcodeDiv?.removeChild(value);
    });
    // @ts-ignore
    let fsredirectUri = `https://passport.feishu.cn/suite/passport/oauth/authorize?client_id=${data.clientId}&redirect_uri=${encodeURIComponent(
      data.redirectUri
    )}&response_type=code&state=${data.state}`;
    // @ts-ignore
    var redirectUri = fsredirectUri;
    // @ts-ignore
    let QRLoginObj = QRLogin({
      id: 'div_qrcodelogin',
      goto: redirectUri,
      width: '300',
      height: '300',
      style: 'border: 0;'
    });
  }

const qrScanDingtalk=(data: any)=> {
    //see doc https://open.dingtalk.com/document/isvapp-server/scan-qr-code-to-log-on-to-third-party-websites
    var url = encodeURIComponent(data.redirectUri);
    var gotodingtalk = encodeURIComponent(
      `https://oapi.dingtalk.com/connect/oauth2/sns_authorize?appid=${data.clientId}&response_type=code&scope=snsapi_login&state=${data.state}&redirect_uri=${url}`
    );
    // @ts-ignore
    let ddredirect_uri = `https://oapi.dingtalk.com/connect/oauth2/sns_authorize?appid=${data.clientId}&response_type=code&scope=snsapi_login&state=${data.state}&redirect_uri=${data.redirectUri}`;
    // @ts-ignore
    var obj = DDLogin({
      id: 'div_qrcodelogin', //这里需要你在自己的页面定义一个HTML标签并设置id，例如<div id="login_container"></div>或<span id="login_container"></span>
      goto: gotodingtalk, //请参考注释里的方式
      style: 'border:none;background-color:#FFFFFF;',
      width: '360',
      height: '400'
    });
  }
</script>

<style lang="less" scoped>
 @import  "../assets/less/login.less";
</style>

// maxkey-web-frontend/maxkey-web-app/src/app/routes/passport/login/login.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Inject, OnInit, OnDestroy, AfterViewInit, Optional } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { throwIfAlreadyLoaded } from '@core';
import { ReuseTabService } from '@delon/abc/reuse-tab';
import { SettingsService, _HttpClient } from '@delon/theme';
import { environment } from '@env/environment';
import { NzSafeAny } from 'ng-zorro-antd/core/types';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzTabChangeEvent } from 'ng-zorro-antd/tabs';
import { finalize } from 'rxjs/operators';

import { AuthenticationService } from '../../../service/authentication.service';
import { ImageCaptchaService } from '../../../service/image-captcha.service';
import { SocialsProviderService } from '../../../service/socials-provider.service';
import { CONSTS } from '../../../shared/consts';

import { stringify } from 'querystring';

@Component({
  selector: 'passport-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.less'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UserLoginComponent implements OnInit, OnDestroy {
  socials: {
    providers: NzSafeAny[];
    qrScan: string;
  } = {
      providers: [],
      qrScan: ''
    };

  form: FormGroup;
  error = '';
  loginType = 'normal';
  loading = false;
  passwordVisible = false;
  imageCaptcha = '';
  captchaType = '';
  state = '';

  count = 0;
  interval$: any;

  constructor(
    fb: FormBuilder,
    private router: Router,
    private settingsService: SettingsService,
    private authenticationService: AuthenticationService,
    private socialsProviderService: SocialsProviderService,
    private imageCaptchaService: ImageCaptchaService,
    @Optional()
    @Inject(ReuseTabService)
    private reuseTabService: ReuseTabService,
    private route: ActivatedRoute,
    private msg: NzMessageService,
    private cdr: ChangeDetectorRef
  ) {
    this.form = fb.group({
      userName: [null, [Validators.required]],
      password: [null, [Validators.required]],
      captcha: [null, [Validators.required]],
      mobile: [null, [Validators.required, Validators.pattern(/^1\d{10}$/)]],
      otpCaptcha: [null, [Validators.required]],
      remember: [false]
    });
  }

  ngOnInit(): void {
    //set redirect_uri , is BASE64URL
    if (this.route.snapshot.queryParams[CONSTS.REDIRECT_URI]) {
      this.authenticationService.setRedirectUri(this.route.snapshot.queryParams[CONSTS.REDIRECT_URI]);
    }

    //congress login
    if (this.route.snapshot.queryParams[CONSTS.CONGRESS]) {
      this.congressLogin(this.route.snapshot.queryParams[CONSTS.CONGRESS]);
    }

    if (localStorage.getItem(CONSTS.REMEMBER) && localStorage.getItem(CONSTS.REMEMBER)?.endsWith('true')) {
      this.authenticationService.navigate({});
      //auto auth
    } else {
      //init socials,state
      this.authenticationService.clear();
      this.authenticationService
        .get({})
        .pipe(
          finalize(() => {
            this.loading = false;
            this.cdr.detectChanges();
          })
        )
        .subscribe(res => {
          this.loading = true;
          if (res.code !== 0) {
            this.error = res.msg;
          } else {
            // 清空路由复用信息
            console.log(res.data);
            this.socials = res.data.socials;
            this.state = res.data.state;
            this.captchaType = res.data.captchaType;
            //init image captcha
            this.imageCaptchaService.captcha({ state: this.state, captcha: this.captchaType }).subscribe(res => {
              this.imageCaptcha = res.data.image;
              this.cdr.detectChanges();
            });
          }
        });
    }
    this.cdr.detectChanges();
  }

  congressLogin(congress: string) {
    this.authenticationService
      .congress({
        congress: congress
      })
      .pipe(
        finalize(() => {
          this.loading = false;
          this.cdr.detectChanges();
        })
      )
      .subscribe(res => {
        this.loading = true;
        if (res.code !== 0) {
          this.error = res.msg;
        } else {
          // 清空路由复用信息
          this.reuseTabService.clear();
          // 设置用户Token信息
          this.authenticationService.auth(res.data);
          this.authenticationService.navigate({});
        }
      });
  }
  // #region fields

  get userName(): AbstractControl {
    return this.form.get('userName')!;
  }
  get password(): AbstractControl {
    return this.form.get('password')!;
  }
  get mobile(): AbstractControl {
    return this.form.get('mobile')!;
  }
  get captcha(): AbstractControl {
    return this.form.get('captcha')!;
  }

  get otpCaptcha(): AbstractControl {
    return this.form.get('otpCaptcha')!;
  }
  // #endregion

  // #region get captcha
  getImageCaptcha(): void {
    this.imageCaptchaService.captcha({ state: this.state, captcha: this.captchaType }).subscribe(res => {
      this.imageCaptcha = res.data.image;
      this.cdr.detectChanges();
    });
  }

  //send sms
  sendOtpCode(): void {
    if (this.mobile.invalid) {
      this.mobile.markAsDirty({ onlySelf: true });
      this.mobile.updateValueAndValidity({ onlySelf: true });
      return;
    }
    this.authenticationService.produceOtp({ mobile: this.mobile.value }).subscribe(res => {
      if (res.code !== 0) {
        this.msg.success(`发送失败`);
      }
    });
    this.count = 59;
    this.interval$ = setInterval(() => {
      this.count -= 1;
      if (this.count <= 0) {
        clearInterval(this.interval$);
      }
      this.cdr.detectChanges();
    }, 1000);
  }

  // #endregion

  submit(): void {
    this.error = '';
    if (this.loginType === 'normal') {
      this.userName.markAsDirty();
      this.userName.updateValueAndValidity();
      this.password.markAsDirty();
      this.password.updateValueAndValidity();
      this.captcha.markAsDirty();
      this.captcha.updateValueAndValidity();
      if (this.userName.invalid || this.password.invalid || this.captcha.invalid) {
        return;
      }
    } else {
      this.mobile.markAsDirty();
      this.mobile.updateValueAndValidity();
      this.otpCaptcha.markAsDirty();
      this.otpCaptcha.updateValueAndValidity();
      if (this.mobile.invalid || this.otpCaptcha.invalid) {
        return;
      }
    }

    localStorage.setItem(CONSTS.REMEMBER, this.form.get(CONSTS.REMEMBER)?.value);

    this.loading = true;
    this.cdr.detectChanges();
    this.authenticationService
      .login({
        authType: this.loginType,
        state: this.state,
        username: this.userName.value,
        password: this.password.value,
        captcha: this.captcha.value,
        mobile: this.mobile.value,
        otpCaptcha: this.otpCaptcha.value
      })
      .pipe(
        finalize(() => {
          this.loading = false;
          this.cdr.detectChanges();
        })
      )
      .subscribe(res => {
        this.loading = true;
        if (res.code !== 0) {
          this.error = '登录失败，请重新登录'; //res.msg;
          //this.msg.success(`登录失败，请重新登录！`);
          if (this.loginType === 'normal') {
            this.getImageCaptcha();
          }
        } else {
          // 清空路由复用信息
          this.reuseTabService.clear();
          // 设置用户Token信息
          this.authenticationService.auth(res.data);
          this.authenticationService.navigate({});
        }
        this.cdr.detectChanges();
      });
  }

  // #region social
  socialauth(provider: string): void {
    this.socialsProviderService.authorize(provider).subscribe(res => {
      //console.log(res.data);
      window.location.href = res.data;
    });
  }

  getQrCode(): void {
    this.socialsProviderService.scanqrcode(this.socials.qrScan).subscribe(res => {
      if (res.code === 0) {
        if (this.socials.qrScan === 'workweixin') {
          this.qrScanWorkweixin(res.data);
        } else if (this.socials.qrScan === 'dingtalk') {
          this.qrScanDingtalk(res.data);
        } else if (this.socials.qrScan === 'feishu') {
          this.qrScanFeishu(res.data);
        }
      }
    });
  }

  // #endregion

  ngOnDestroy(): void {
    if (this.interval$) {
      clearInterval(this.interval$);
    }
  }

  // #region QR Scan for workweixin, dingtalk ,feishu
  qrScanWorkweixin(data: any) {
    //see doc https://developer.work.weixin.qq.com/document/path/91025
    // @ts-ignore
    let wwLogin = new WwLogin({
      id: 'div_qrcodelogin',
      appid: data.clientId,
      agentid: data.agentId,
      redirect_uri: encodeURIComponent(data.redirectUri),
      state: data.state,
      href: 'data:text/css;base64,LmltcG93ZXJCb3ggLnFyY29kZSB7d2lkdGg6IDI1MHB4O30NCi5pbXBvd2VyQm94IC50aXRsZSB7ZGlzcGxheTogbm9uZTt9DQouaW1wb3dlckJveCAuaW5mbyB7d2lkdGg6IDI1MHB4O30NCi5zdGF0dXNfaWNvbiB7ZGlzcGxheTpub25lfQ0KLmltcG93ZXJCb3ggLnN0YXR1cyB7dGV4dC1hbGlnbjogY2VudGVyO30='
    });
  }

  qrScanFeishu(data: any) {
    //see doc https://open.feishu.cn/document/common-capabilities/sso/web-application-sso/qr-sdk-documentation
    //remove old div
    var qrcodeDiv = document.querySelector('#div_qrcodelogin');
    qrcodeDiv?.childNodes.forEach(function (value, index, array) {
      qrcodeDiv?.removeChild(value);
    });
    // @ts-ignore
    fsredirectUri = `https://passport.feishu.cn/suite/passport/oauth/authorize?client_id=${data.clientId}&redirect_uri=${encodeURIComponent(
      data.redirectUri
    )}&response_type=code&state=${data.state}`;
    // @ts-ignore
    var redirectUri = fsredirectUri;
    // @ts-ignore
    QRLoginObj = QRLogin({
      id: 'div_qrcodelogin',
      goto: redirectUri,
      width: '300',
      height: '300',
      style: 'border: 0;'
    });
  }

  qrScanDingtalk(data: any) {
    //see doc https://open.dingtalk.com/document/isvapp-server/scan-qr-code-to-log-on-to-third-party-websites
    var url = encodeURIComponent(data.redirectUri);
    var gotodingtalk = encodeURIComponent(
      `https://oapi.dingtalk.com/connect/oauth2/sns_authorize?appid=${data.clientId}&response_type=code&scope=snsapi_login&state=${data.state}&redirect_uri=${url}`
    );
    // @ts-ignore
    ddredirect_uri = `https://oapi.dingtalk.com/connect/oauth2/sns_authorize?appid=${data.clientId}&response_type=code&scope=snsapi_login&state=${data.state}&redirect_uri=${data.redirectUri}`;
    // @ts-ignore
    var obj = DDLogin({
      id: 'div_qrcodelogin', //这里需要你在自己的页面定义一个HTML标签并设置id，例如<div id="login_container"></div>或<span id="login_container"></span>
      goto: gotodingtalk, //请参考注释里的方式
      style: 'border:none;background-color:#FFFFFF;',
      width: '360',
      height: '400'
    });
  }
  // #region QR Scan end
}

<form nz-form [formGroup]="form" (ngSubmit)="submit()" role="form">
  <nz-radio-group
    [(ngModel)]="loginType"
    [ngModelOptions]="{ standalone: true }"
    nzSize="large"
    *ngIf="switchTab"
    style="margin-bottom: 8px; width: 100%"
  >
    <label nz-radio-button nzValue="normal" style="width: 50%; text-align: center">
      <i nz-icon nzType="user" nzTheme="outline"></i>
      {{ 'mxk.login.tab-credentials' | i18n }}
    </label>
    <label nz-radio-button nzValue="mobile" style="width: 50%; text-align: center" class="d-none">
      <i nz-icon nzType="mobile" nzTheme="outline"></i>
      {{ 'mxk.login.tab-mobile' | i18n }}
    </label>
    <label nz-radio-button nzValue="qrscan" style="width: 50%; text-align: center" (click)="getScanQrCode()">
      <i nz-icon nzType="qrcode" nzTheme="outline"></i>{{ 'mxk.login.tab-qrscan' | i18n }}
    </label>
  </nz-radio-group>
  <div nz-row *ngIf="loginType == 'normal'">
    <nz-alert style="width: 100%" *ngIf="error" [nzType]="'error'" [nzMessage]="error" [nzShowIcon]="true" class="mb-lg"></nz-alert>
    <nz-form-item style="width: 100%">
      <nz-form-control nzErrorTip="">
        <nz-input-group nzSize="large" nzPrefixIcon="user">
          <input nz-input formControlName="userName" placeholder="{{ 'mxk.login.text.username' | i18n }}" />
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item style="width: 100%">
      <nz-form-control nzErrorTip="">
        <nz-input-group [nzSuffix]="suffixTemplate" nzSize="large" nzPrefixIcon="key">
          <input
            [type]="passwordVisible ? 'text' : 'password'"
            nz-input
            placeholder="{{ 'mxk.login.text.password' | i18n }}"
            formControlName="password"
          />
        </nz-input-group>
        <ng-template #suffixTemplate>
          <i nz-icon [nzType]="passwordVisible ? 'eye-invisible' : 'eye'" (click)="passwordVisible = !passwordVisible"></i>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item style="width: 100%" *ngIf="captchaType != 'NONE'">
      <nz-form-control nzErrorTip="">
        <nz-input-group nzSearch nzSize="large" nzPrefixIcon="lock" nzSearch [nzAddOnAfter]="suffixImageCaptchaButton">
          <input type="text" formControlName="captcha" nz-input placeholder="{{ 'mxk.login.text.captcha' | i18n }}" />
        </nz-input-group>
        <ng-template #suffixImageCaptchaButton>
          <img src="{{ imageCaptcha }}" (click)="getImageCaptcha()" />
        </ng-template>
      </nz-form-control>
    </nz-form-item>
  </div>
  <div nz-row *ngIf="loginType == 'mobile'">
    <nz-form-item style="width: 100%">
      <nz-form-control [nzErrorTip]="">
        <nz-input-group nzSize="large" nzPrefixIcon="user">
          <input nz-input formControlName="mobile" placeholder="{{ 'mxk.login.text.mobile' | i18n }}" />
        </nz-input-group>
        <ng-template #mobileErrorTip let-i>
          <ng-container *ngIf="i.errors.required">
            {{ 'validation.phone-number.required' | i18n }}
          </ng-container>
          <ng-container *ngIf="i.errors.pattern">
            {{ 'validation.phone-number.wrong-format' | i18n }}
          </ng-container>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item style="width: 100%">
      <nz-form-control [nzErrorTip]="'' | i18n">
        <nz-input-group nzSize="large" nzPrefixIcon="mail" nzSearch [nzAddOnAfter]="suffixSendOtpCodeButton">
          <input nz-input formControlName="otpCaptcha" placeholder="{{ 'mxk.login.text.captcha' | i18n }}" />
        </nz-input-group>
        <ng-template #suffixSendOtpCodeButton>
          <button type="button" nz-button nzSize="large" (click)="sendOtpCode()" [disabled]="count > 0" nzBlock [nzLoading]="loading">
            {{ count ? count + 's' : ('app.register.get-verification-code' | i18n) }}
          </button>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
  </div>
  <div nz-row *ngIf="loginType == 'qrscan'">
    <div class="qrcode" id="div_qrcodelogin" style="background: #fff; padding: 20px"></div>
    <div id="qrexpire" *ngIf="qrexpire" style="width: 100%; text-align: center; background: #fff; padding-bottom: 20px">
      二维码过期 <a href="javascript:void(0);" (click)="getScanQrCode()">刷新</a>
    </div>
  </div>
  <nz-form-item *ngIf="loginType == 'normal' || loginType == 'mobile'">
    <nz-col [nzSpan]="12">
      <label nz-checkbox formControlName="remember">{{ 'mxk.login.remember-me' | i18n }}</label>
    </nz-col>
    <nz-col [nzSpan]="12" class="text-right">
      <a class="forgot" routerLink="/passport/forgot">{{ 'mxk.login.forgot-password' | i18n }}</a>
    </nz-col>
  </nz-form-item>
  <nz-form-item *ngIf="loginType == 'normal' || loginType == 'mobile'">
    <button nz-button type="submit" nzType="primary" nzSize="large" [nzLoading]="loading" nzBlock>
      {{ 'app.login.login' | i18n }}
    </button>
  </nz-form-item>
  <nz-form-item *ngIf="loginType == 'normal'">
      <button nz-button type="button" nzType="default" nzSize="large" (click)="passkeyLogin()" nzBlock>
        <i nz-icon nzType="safety-certificate" nzTheme="outline"></i>
        {{ 'mxk.login.passkey-login' | i18n }}
      </button>
    </nz-form-item>
</form>
<div class="other" *ngIf="loginType == 'normal'">
  {{ 'app.login.sign-in-with' | i18n }}
  <ng-container *ngFor="let provd of socials.providers">
    <i nz-tooltip nzTooltipTitle="{{ provd.providerName }}" (click)="socialauth(provd.provider)" nz-icon class="icon">
      <img src="{{ provd.icon }}" style="width: 32px" />
    </i>
  </ng-container>
  <a class="register d-none" routerLink="/passport/register">{{ 'mxk.login.signup' | i18n }}</a>
</div>
