// summer-ospp/2022/MaxKey-vue/src/components/Jwt-auth.vue
<script lang="ts" setup>
import {onBeforeMount} from "vue"
import {useRoute,useRouter} from "vue-router"
import {api} from "../utils/api"
let jwt = ''
const route = useRoute()
const router = useRouter()
onBeforeMount(()=>{
    jwt = route.query['jwt'] as string
    api.jwtAuth({jwt})
    .then((res)=>{
        res=res.data
        if(res.code != 0){
            router.push('/passport/login')
        }else{
            api.auth(res.data)
            api.navigate({})
        }
    })
})
</script>

// summer-ospp/2022/MaxKey-React/src/routes/Jwt-auth.tsx
import React, { useEffect } from "react"
import { useSearchParams ,useNavigate} from "react-router-dom"
import {api} from "../utils/api"
import { AxiosResponse } from "axios"
export default function JwtAuth(){
    let jwt = ''
    let [searchParams] = useSearchParams()
    const navigate = useNavigate()
    useEffect(()=>{
        jwt = searchParams.get('jwt')!
        api.jwtAuth({jwt})
        .then((response:AxiosResponse)=>{
            const res = response.data
            if(res.code !==0) {
                navigate('/passport/login',{replace:true})
            }else{
                api.auth(res.data)
                api.navigate({})
            }
        })
    },[])
    return(
        <>
        </>
    )
}
