// summer-ospp/2022/MaxKey-vue/src/components/User.vue
<template>
 <el-form :inline="true" :model="form" label-width="180px" class="demo-form-inline">
    <el-form-item label="姓:">
        <el-input v-model="form.familyName"></el-input>
    </el-form-item>
     <el-form-item label="中间名:">
        <el-input v-model="form.middleName"></el-input>
    </el-form-item>
    <el-form-item label="名:">
        <el-input v-model="form.givenName"></el-input>
    </el-form-item>
    <el-form-item label="昵称:">
        <el-input v-model="form.nickName"></el-input>
    </el-form-item>
    <el-form-item label="证件类型:">
        <el-select v-model="form.cardType" placeholder="身份证">
            <el-option label="未知" value="未知"></el-option>
            <el-option label="身份证" value="身份证"></el-option>
            <el-option label="护照" value="护照"></el-option>
            <el-option label="学生证" value="学生证"></el-option>
            <el-option label="军人证" value="军人证"></el-option>
        </el-select>
    </el-form-item>
    <el-form-item label="证件号码:">
        <el-input v-model="form.IdCardNo"></el-input>
    </el-form-item>
    <el-form-item label="婚姻状态:">
        <el-select v-model="form.marriage" placeholder="未知">
            <el-option label="未知" value="未知"></el-option>
            <el-option label="单身" value="单身"></el-option>
            <el-option label="已婚" value="已婚"></el-option>
            <el-option label="离异" value="离异"></el-option>
            <el-option label="丧偶" value="丧偶"></el-option>
        </el-select>
    </el-form-item>
    <el-form-item label="出生日期:">
        <el-input v-model="form.birthday"></el-input>
    </el-form-item>
    <el-form-item label="语言偏好:">
        <el-input v-model="form.preferredLanguage"></el-input>
    </el-form-item>
    <el-form-item label="工作开始时间:">
        <el-input v-model="form.workStart"></el-input>
    </el-form-item>
    <el-form-item label="个人主页:">
        <el-input v-model="form.webSite"></el-input>
    </el-form-item>
    <el-form-item label="即时通讯:">
        <el-input v-model="form.phone"></el-input>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="onSubmit">提交</el-button>
    </el-form-item>
 </el-form>
</template>

<script lang="ts" setup>
import {reactive,onBeforeMount} from "vue"
import {ElForm,ElFormItem,ElInput,ElSelect,ElOption,ElButton, ElMessage} from "element-plus"
import {api} from "../utils/api"
import {AxiosResponse,AxiosError} from "axios"
interface Form{
    familyName: string,
    middleName: string,
    givenName: string,
    nickName: string,
    cardType: string,
    IdCardNo: string,
    marriage: string,
    birthday: string,
    preferredLanguage: string,
    workStart: string,
    webSite: string,
    phone: string
}

let form = reactive<Form>({
    familyName:'',
    middleName: '',
    givenName: '',
    nickName: '',
    cardType: '',
    IdCardNo: '',
    marriage: '',
    birthday: '',
    preferredLanguage: '',
    workStart: '',
    webSite: '',
    phone: '',
})
onBeforeMount(()=>{
    api.getProfile()
    .then((res:AxiosResponse)=>{
        console.log(res.data)
        res=res.data
        if(res.code===0){           
            form.familyName=res.data.familyName
            form.middleName=res.data.middleName
            form.givenName = res.data.givenName
            form.nickName = res.data.nickName
            form.IdCardNo = res.data.idCardNo
            form.preferredLanguage = res.data.preferredLanguage
            form.webSite = res.data.webSite
        }
    })
    .catch((err:AxiosError)=>{
        Promise.reject(err)
        ElMessage.error(err.message)
    })

})
const onSubmit=(e:MouseEvent):void=>{
    e.preventDefault()
    api.updateProfile(form)
    .then((res)=>{
        res=res.data
        if(res.code === 0){
            ElMessage.success("更新成功")
            localStorage.setItem("user",JSON.stringify(form))
        }else{
             ElMessage.error("更新失败")
        }
    })
    .catch(err=>{
        Promise.reject(err)
        ElMessage.error(err.message)
    })
}
</script>

<style lang="less">
.el-form {
    background-color: #fff;
    padding:50px 0;
   
}
.el-form-item {
    margin-right: 0 !important
}
.el-button {
    display: block;
}
.el-input {
    width: 358px;
}
</style>

// summer-ospp/2022/MaxKey-React/src/routes/User.tsx
/* eslint-disable no-template-curly-in-string */
import React,{useEffect,useState}  from "react"
import {Button,Form,Input,Select,message,Spin} from 'antd'
import useSyncCallback from "../hook/useSyncCallback"
import {AxiosResponse,AxiosError} from "axios"
import {api} from "../utils/api"
import "../assets/scss/user.scss"
const {Option} = Select
const validateMessages = {
    required: '${label} is required!',
    types: {
      number: '${label} is not a valid number!',      
    },
  };
export default function User() {
    const [form] =Form.useForm()
    //let formValue = useRef(null)
    const [formjson,setFormJson] = useState({})
    const [loading,setLoading] = useState(true)
    const onFinish=(values:any)=>{
        //console.log(values)
        api.updateProfile(values)
        .then((response:AxiosResponse)=>{
            const res=response.data
            if(res.code === 0){
                message.success("更新成功")
                localStorage.setItem("user",JSON.stringify(values))
            }else{
                message.error("更新失败")
            }
        })
        .catch((err:AxiosError)=>{
            Promise.reject(err)
            message.error(err.message)
        })
        
    }
   const func= useSyncCallback(()=>{
        console.log(formjson)
        form.resetFields()
        setLoading(false) 
   })
    
    useEffect(()=>{
        api.getProfile()
        .then((response:AxiosResponse)=>{           
            const res=response.data
            if(res.code===0){ 
                setFormJson({
                    familyName:res.data.familyName,
                    middleName:res.data.middleName,
                    givenName : res.data.givenName,
                    nickName : res.data.nickName,
                    idCardNo : res.data.idCardNo,
                    preferredLanguage : res.data.preferredLanguage,
                    webSite : res.data.webSite,
                })
                func();                              
            }
        })
        .catch((err:AxiosError)=>{
            Promise.reject(err)
            message.error(err.message)
        })
    },[form])
    
    return (
        <>
        <Spin spinning = {loading}>          
            <Form 
                form={form}
                onFinish={onFinish}
                validateMessages={validateMessages}
                initialValues={formjson}
                >               
                    <Form.Item  name='familyName' label="姓:">
                        <Input />
                    </Form.Item>
                    <Form.Item  name='middleName' label="中间名:">
                        <Input />
                    </Form.Item>
                            
                    <Form.Item name='givenName' label="名:">
                        <Input/>
                    </Form.Item>
                    <Form.Item name='nickName' label="昵称:">
                        <Input/>
                    </Form.Item>
                    <Form.Item  label="证件类型:">
                        <Select defaultValue="身份证">
                            <Option value="未知">未知</Option>
                            <Option value="身份证">身份证</Option>
                            <Option value="护照">护照</Option>
                            <Option value="学生证">学生证</Option>
                            <Option value="军人证">军人证</Option>
                        </Select>
                    </Form.Item>
                    
                    <Form.Item name='idCardNo' label="证件号码:" rules={[{type:'number'}]}>
                        <Input/>
                    </Form.Item>
                    <Form.Item label="婚姻状态:">
                        <Select defaultValue="未知">
                            <Option value="未知">未知</Option>
                            <Option value="单身">单身</Option>
                            <Option value="已婚">已婚</Option>
                            <Option value="离异">离异</Option>
                            <Option value="丧偶">丧偶</Option>
                        </Select>
                    </Form.Item>
                    
                    <Form.Item name='birthday' label="出生日期:" >
                        <Input/>
                    </Form.Item>
                    <Form.Item name='preferredLanguage'label="语言偏好:">
                        <Input/>
                    </Form.Item>
                    <Form.Item name='workStart' label="工作开始时间:" >
                        <Input/>
                    </Form.Item> 
                    <Form.Item name='webSite' label="个人主页:">
                        <Input/>
                    </Form.Item> 
                    <Form.Item name='phone' label="即时通讯:">
                        <Input/>
                    </Form.Item> 
                    <Form.Item >
                        <Button type="primary" htmlType="submit">
                        提交
                        </Button>
                    </Form.Item>
            </Form>
        </Spin>   
        </>
    )
       
}
